set -euo pipefail

NIXORCIST_MARKER='#$nixorcist$#'
BUILT_MARKER='#$built$#'

: "${LOCK_FILE:?LOCK_FILE not set}"
: "${MODULES_DIR:?MODULES_DIR not set}"

read_lock_entries() {
  grep -v -F "$BUILT_MARKER" "$LOCK_FILE" 2>/dev/null \
    | sed '/^[[:space:]]*$/d' | sort -u
}

select_packages() {
  echo
  echo "1) Add / Keep packages"
  echo "2) Remove packages"
  echo "3) Skip"
  read -p "Choose [1-3]: " action

  case "$action" in
    1|"") add_packages ;;
    2) remove_packages ;;
    *) echo "Skipped." ;;
  esac
}

run_rebuild() {
  local rebuild_script="/etc/nixos/scripts/nix-rebuild-smart.sh"

  if [[ ! -x "$rebuild_script" ]]; then
    echo "Rebuild script not found or not executable: $rebuild_script"
    exit 1
  fi

  echo "Starting smart rebuild..."
  exec "$rebuild_script"
}

add_packages() {
  source "$ROOT/lib/transaction.sh"
  transaction_menu
}




remove_packages() {
  source "$ROOT/lib/transaction.sh"
  transaction_menu
}

# ===============================
# IMPORT FROM FILE LOGIC
# ===============================

import_from_file() {
  local file="$1"
  [[ -z "$file" || ! -f "$file" ]] && { echo "Provide a valid text file."; return 1; }
  # Parse file, normalize, and present interactive selection
  normalized=$(tr ',\n ' '|||' < "$file" | tr -s '|' | sed 's/^|//;s/|$//' | tr '[:upper:]' '[:lower:]')
  IFS='|' read -ra requested <<< "$normalized"
  mapfile -t nixpkgs_list < <(list_available_packages_lower)
  valid_pkgs=()
  for pkg in "${requested[@]}"; do
    [[ -z "$pkg" ]] && continue
    if package_exists "$pkg"; then
      valid_pkgs+=("$pkg")
    elif is_attrset "$pkg"; then
      mapfile -t variants < <(list_attrset_children "$pkg")
      for v in "${variants[@]}"; do
        valid_pkgs+=("$pkg.$v")
      done
    fi
  done
  # Interactive selection for import
  selected=$(printf '%s\n' "${valid_pkgs[@]}" | fzf --multi --prompt="IMPORT> " --preview 'get_pkg_description {}')
  [[ -z "$selected" ]] && { echo "Nothing selected."; return 1; }
  # Add to lock
  mapfile -t current_lock < <(read_lock_entries)
  for pkg in $selected; do
    grep -qx "$pkg" "$LOCK_FILE" || current_lock+=("$pkg")
  done
  printf '%s\n' "${current_lock[@]}" | sort -u > "$LOCK_FILE"
  echo "$BUILT_MARKER" >> "$LOCK_FILE"
  echo
  read -p "Import finished. Run full pipeline (all)? [y/N]: " answer
  case "${answer,,}" in
    y)
      select_packages
      generate_modules
      regenerate_hub
      run_rebuild
      ;;
    *)
      echo "Import complete. No full pipeline triggered."
      ;;
  esac
}

scan_managed_modules() {
  shopt -s nullglob

  for f in "$MODULES_DIR"/*.nix; do
    # Only consider modules generated by nixorcist
    if grep -qF "$NIXORCIST_MARKER" "$f" 2>/dev/null; then
      grep -E '^[[:space:]]*#[[:space:]]*NIXORCIST-ATTRPATH:' "$f" \
        | head -1 \
        | sed 's/^[[:space:]]*#[[:space:]]*NIXORCIST-ATTRPATH:[[:space:]]*//'
    fi
  done | sort -u

  shopt -u nullglob
}

package_exists() {
  local name="$1"
  local -n list_ref=$2
  for p in "${list_ref[@]}"; do
    [[ "$p" == "$name" ]] && return 0
  done
  return 1
}

handle_missing_package() {
  local missing="$1"
  local -n pkgs_ref=$2
  local -n lock_ref=$3

  mapfile -t matches < <(printf '%s\n' "${pkgs_ref[@]}" \
    | grep -i "$missing" | head -10)

  if (( ${#matches[@]} == 0 )); then
    echo "  No matches found. Skipping."
    return
  fi

  echo "  Similar packages:"
  printf '   - %s\n' "${matches[@]}"

  read -p "  Auto-rename to first match? [Y/n/c]: " answer

  case "${answer,,}" in
    ""|"y")
      selected="${matches[0]}"
      ;;
    c)
      selected=$(printf '%s\n' "${matches[@]}" | \
        fzf --prompt="Choose rename> ")
      ;;
    *)
      echo "  skipped."
      return
      ;;
  esac

  [[ -z "$selected" ]] && return

  # -------- NEW LOGIC --------

  if is_derivation "$selected"; then
    lock_ref+=("$selected")
    echo "✓ resolved: $selected"
    return
  fi

  if is_attrset "$selected"; then
    echo "  Namespace detected: $selected"

    mapfile -t variants < <(
      list_attrset_children "$selected" | fzf \
        --multi \
        --header="TAB to select multiple packages" \
        --prompt="Select $selected variants > "
    )

    [[ ${#variants[@]} -eq 0 ]] && return

    for variant in "${variants[@]}"; do
      resolved="$selected.$variant"

      if is_derivation "$resolved"; then
        lock_ref+=("$resolved")
        echo "✓ resolved: $resolved"
      else
        echo "  Skipping non-package: $resolved"
      fi
    done

    return
  fi

  echo "  Not a valid package. Skipping."
}



