set -euo pipefail

NIXORCIST_MARKER='#$nixorcist$#'
BUILT_MARKER='#$built$#'

: "${LOCK_FILE:?LOCK_FILE not set}"
: "${MODULES_DIR:?MODULES_DIR not set}"

read_lock_entries() {
  grep -v -F "$BUILT_MARKER" "$LOCK_FILE" 2>/dev/null \
    | sed '/^[[:space:]]*$/d' | sort -u
}

select_packages() {
  echo
  echo "1) Add / Keep packages"
  echo "2) Remove packages"
  echo "3) Skip"
  read -p "Choose [1-3]: " action

  case "$action" in
    1|"") add_packages ;;
    2) remove_packages ;;
    *) echo "Skipped." ;;
  esac
}

run_rebuild() {
  local rebuild_script="/etc/nixos/scripts/nix-rebuild-smart.sh"

  if [[ ! -x "$rebuild_script" ]]; then
    echo "Rebuild script not found or not executable: $rebuild_script"
    exit 1
  fi

  echo "Starting smart rebuild..."
  exec "$rebuild_script"
}

add_packages() {
  mapfile -t current < <(read_lock_entries)
  mapfile -t full_list < <(list_available_packages)

  selected=$(printf '%s\n' "${full_list[@]}" | \
    fzf --multi --prompt="PACKAGES> ")

  [[ -z "$selected" ]] && return

  printf '%s\n' $selected | sort -u > "$LOCK_FILE"
  echo "$BUILT_MARKER" >> "$LOCK_FILE"
  echo "Lock updated."
}

remove_packages() {
  mapfile -t current < <(read_lock_entries)

  selected=$(printf '%s\n' "${current[@]}" | \
    fzf --multi --prompt="REMOVE> ")

  [[ -z "$selected" ]] && return

  tmp=()
  while IFS= read -r entry; do
    for c in "${current[@]}"; do
      [[ "$c" == "$entry" ]] && continue
      tmp+=("$c")
    done
  done <<< "$selected"

  printf '%s\n' "${tmp[@]}" | sort -u > "$LOCK_FILE"
  echo "$BUILT_MARKER" >> "$LOCK_FILE"
  echo "Removed from lock."
}

# ===============================
# IMPORT FROM FILE LOGIC
# ===============================

import_from_file() {
  local file="$1"

  while :; do
    [[ -z "$file" || ! -f "$file" ]] && {
      echo "Provide a valid text file."
      return 1
    }

    echo
    echo "Reading $file"

    # Normalize separators → lowercase
    normalized=$(tr ',\n ' '|||' < "$file" \
      | tr -s '|' \
      | sed 's/^|//;s/|$//' \
      | tr '[:upper:]' '[:lower:]')

    IFS='|' read -ra requested <<< "$normalized"

    mapfile -t nixpkgs_list < <(list_available_packages_lower)
    mapfile -t current_lock < <(read_lock_entries)

    for pkg in "${requested[@]}"; do
      [[ -z "$pkg" ]] && continue

      if package_exists "$pkg" nixpkgs_list; then
        echo "✓ exact: $pkg"
        current_lock+=("$pkg")
      else
        echo "✗ not found: $pkg"
        handle_missing_package "$pkg" nixpkgs_list current_lock
      fi
    done

    printf '%s\n' "${current_lock[@]}" | sort -u > "$LOCK_FILE"
    echo "$BUILT_MARKER" >> "$LOCK_FILE"

    echo
    read -p "Import finished. Rebuild now? [Y/n/m]: " answer

    case "${answer,,}" in
      ""|"y")
        generate_modules
        regenerate_hub
        run_rebuild
        return
        ;;
      m)
        read -p "Enter next file path: " file
        continue
        ;;
      *)
        echo "Import complete. No rebuild triggered."
        return
        ;;
    esac
  done
}

scan_managed_modules() {
  shopt -s nullglob

  for f in "$MODULES_DIR"/*.nix; do
    # Only consider modules generated by nixorcist
    if grep -qF "$NIXORCIST_MARKER" "$f" 2>/dev/null; then
      grep -E '^[[:space:]]*#[[:space:]]*NIXORCIST-ATTRPATH:' "$f" \
        | head -1 \
        | sed 's/^[[:space:]]*#[[:space:]]*NIXORCIST-ATTRPATH:[[:space:]]*//'
    fi
  done | sort -u

  shopt -u nullglob
}

package_exists() {
  local name="$1"
  local -n list_ref=$2
  for p in "${list_ref[@]}"; do
    [[ "$p" == "$name" ]] && return 0
  done
  return 1
}

handle_missing_package() {
  local missing="$1"
  local -n pkgs_ref=$2
  local -n lock_ref=$3

  mapfile -t matches < <(printf '%s\n' "${pkgs_ref[@]}" \
    | grep -i "$missing" | head -10)

  if (( ${#matches[@]} == 0 )); then
    echo "  No matches found. Skipping."
    return
  fi

  echo "  Similar packages:"
  printf '   - %s\n' "${matches[@]}"

  read -p "  Auto-rename to first match? [Y/n/c]: " answer

  case "${answer,,}" in
    ""|"y")
      lock_ref+=("${matches[0]}")
      ;;
    c)
      selected=$(printf '%s\n' "${matches[@]}" | \
        fzf --prompt="Choose rename> ")
      [[ -n "$selected" ]] && lock_ref+=("$selected")
      ;;
    n|*)
      echo "  skipped."
      ;;
  esac
}
