{ config, pkgs, lib, ... }:

# =============================================================================
#                           🧠 CONFIG OVERVIEW
# =============================================================================
# This is a modular NixOS configuration driven by feature flags.
#
# 👉 New users:
# - You ENABLE/DISABLE functionality using the `features` block below.
# - Most logic is conditionally included via `lib.optionals` or `lib.mkIf`.
# - If something breaks, check which feature introduced it.
#
# ⚠️ Rule of thumb:
# - If you don't understand a module → don't delete it, disable its feature.
# - If you add a new feature → follow the same pattern used here.
#
# =============================================================================


# =============================================================================
#                           🚀 FEATURE TOGGLES
# =============================================================================
# Toggle system-wide functionality here.
# These flags control imports, packages, and services across the config.
#
# ✔ true  = enable feature
# ❌ false = completely remove it from system
#
# NOTE:
# This configuration uses separate package groups, so usually disabling one feature
# will not break dependencies.
# However some features can depend on others implicitly (e.g., KDE + Hyprland integration).
# This config does NOT enforce dependencies automatically—you're responsible.
#
let
  features = {
    hyprland = true;        # Wayland compositor (tiling WM)
    kde = true;             # KDE runtime components (not full Plasma session)
    steam = true;           # Gaming stack (Steam + GameMode)
    uwu = true;             # Meme / aesthetic / optional nonsense
    virtualisation = true;  # Docker + VirtualBox support
    nixorcist = true;       # Custom package automation system
    openssh = true;         # Remote access via SSH
  };

in
{

  # ===========================================================================
  # 📦 IMPORTS (MODULE SYSTEM ENTRY POINT)
  # ===========================================================================
  # This is where the system is assembled.
  #
  # Order matters ONLY when modules override each other.
  # Keep things grouped logically.
  #
  imports =
    [
      # --- Core system ---
      ./hardware-configuration.nix   # Generated by NixOS installer (DO NOT DELETE)

      # --- Boot ---
      ./modules/bootloader.nix
      ./modules/grub-theme.nix
      ./modules/kernel-params.nix

      # --- Display/Login ---
      ./modules/sddm.nix

      # --- Core system behavior ---
      ./modules/locale.nix
      ./modules/networking.nix
      ./modules/users.nix
      ./modules/audio.nix

      # --- Shell / environment ---
      ./modules/environment.nix
      ./modules/zsh.nix
      ./modules/rebuild-error-hook.nix

      # --- Compatibility ---
      ./modules/nix-ld.nix

      # --- Auto-generated packages by Nixorcist ---
      ./nixorcist/generated/all-packages.nix
    ]

    # --- Feature-gated modules ---
    ++ lib.optionals features.hyprland [
      ./modules/window-managers.nix
    ]

    ++ lib.optionals features.uwu [
      ./modules/uwu/nixowos.nix
    ]

    ++ lib.optionals features.virtualisation [
      ./modules/virtualbox.nix
    ];


  # ===========================================================================
  # 🔤 FONTS
  # ===========================================================================
  # Provides patched fonts with icons (important for terminals, bars, etc.)
  #
  fonts = {
    fontDir.enable = true;
    packages = with pkgs; [
      nerd-fonts.jetbrains-mono   # Main programming font
      nerd-fonts.symbols-only     # Extra glyphs/icons
    ];
  };


  # ===========================================================================
  # 🖥️ HARDWARE
  # ===========================================================================
  # Enables GPU acceleration and 32-bit compatibility (needed for Steam)
  #
  hardware.graphics.enable = true;
  hardware.graphics.enable32Bit = true;


  # ===========================================================================
  # 🔊 AUDIO
  # ===========================================================================
  # PipeWire replaces PulseAudio + JACK
  #
  services.pipewire.enable = true;


  # ===========================================================================
  # 🪟 WINDOW MANAGER
  # ===========================================================================
  # Hyprland is only enabled if the feature is on
  #
  programs.hyprland.enable = features.hyprland;


  # ===========================================================================
  # 🎨 KDE RUNTIME (NOT FULL KDE DESKTOP)
  # ===========================================================================
  # This provides KDE libraries + integration for apps.
  #
  # ⚠️ This does NOT install Plasma itself.
  #
  qt = lib.mkIf features.kde {
    enable = true;
    platformTheme = "kde";
  };

  # Fixes missing QML modules (common KDE runtime issue)
  environment.sessionVariables = lib.mkIf features.kde {
    QML2_IMPORT_PATH = lib.mkForce (
      lib.concatStringsSep ":" [
        "${pkgs.libsForQt5.qtgraphicaleffects}/lib/qt-5/qml"
        "${pkgs.libsForQt5.kcmutils}/lib/qt-5/qml"
        "${pkgs.libsForQt5.knewstuff}/lib/qt-5/qml"
      ]
    );
  };

  # KDE Polkit agent (required for GUI authentication dialogs)
  systemd.user.services.polkit-kde-agent = lib.mkIf features.kde {
    description = "Polkit KDE Authentication Agent";

    # Starts when Hyprland session starts
    after = [ "hyprland-session.target" ];
    wantedBy = [ "hyprland-session.target" ];

    serviceConfig = {
      ExecStart =
        "${pkgs.kdePackages.polkit-kde-agent-1}/libexec/polkit-kde-authentication-agent-1";
      Restart = "on-failure";
    };
  };

  # Fixes application menu entries for KDE apps
  environment.etc."xdg/menus/applications.menu".source =
    lib.mkIf features.kde
      "${pkgs.kdePackages.plasma-workspace}/etc/xdg/menus/plasma-applications.menu";


  # ===========================================================================
  # 🌐 NETWORKING (SSH)
  # ===========================================================================
  # Enables remote access.
  #
  # ⚠️ SECURITY NOTE:
  # - Password auth is enabled → convenient but less secure
  # - Consider switching to SSH keys later
  #
  services.openssh = lib.mkIf features.openssh {
    enable = true;
    settings = {
      PermitRootLogin = "no";
      PasswordAuthentication = true;
    };
  };


  # ===========================================================================
  # 📦 VIRTUALISATION
  # ===========================================================================
  # Docker is controlled by feature flag
  #
  virtualisation.docker.enable = features.virtualisation;


  # ===========================================================================
  # 🎮 GAMING
  # ===========================================================================
  # Steam + performance tweaks
  #
  programs.steam = lib.mkIf features.steam {
    enable = true;
    gamescopeSession.enable = true; # Better fullscreen handling
  };

  programs.gamemode.enable = features.steam;


  # ===========================================================================
  # ⚙️ NIX SETTINGS
  # ===========================================================================
  # Global Nix behavior tweaks
  #
  nixpkgs.config.allowUnfree = true; # Needed for Steam, etc.

  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];

    # Performance tuning (safe defaults)
    download-buffer-size = 324217728;
    http-connections = 50;
  };


  # ===========================================================================
  # 📦 SYSTEM PACKAGES
  # ===========================================================================
  # This aggregates packages from multiple sources.
  #
  # Structure:
  # 1. Global packages
  # 2. Feature-specific packages
  # 3. Forced always-installed tools
  #
  environment.systemPackages =

    # --- Global packages ---
    (import ./packages/all-packages.nix { inherit pkgs; })

    # --- Feature-based packages ---
    ++ lib.optionals features.kde
      (import ./packages/kde.nix { inherit pkgs; })

    ++ lib.optionals features.hyprland
      (import ./packages/hyprland.nix { inherit pkgs; })

    ++ lib.optionals features.steam
      (import ./packages/games.nix { inherit pkgs; })

    ++ lib.optionals features.nixorcist
      (import ./packages/autogenerated.nix { inherit pkgs; })

    # --- Always-installed utilities ---
    ++ [
      pkgs.kdePackages.polkit-kde-agent-1
      pkgs.kdePackages.kio-admin
      pkgs.hyprland-qt-support

      # Wrapper for nixorcist script
      (pkgs.writeShellScriptBin "nixorcist" ''
        exec /etc/nixos/nixorcist/nixorcist.sh "$@"
      '')
    ];


  # ===========================================================================
  # 🧾 STATE VERSION
  # ===========================================================================
  # DO NOT CHANGE unless you know what you're doing.
  #
  # This locks behavior for backward compatibility.
  #
  system.stateVersion = "25.11";

}
