{ pkgs }:

let
  core = import ./core.nix { inherit pkgs; };
  dev = import ./development.nix { inherit pkgs; };
  kde = import ./kde.nix { inherit pkgs; };
  hypr = import ./hyprland.nix { inherit pkgs; };
  games = import ./games.nix { inherit pkgs; };
  comms = import ./communication.nix { inherit pkgs; };
  simplex = import ./simplex-chat.nix { inherit pkgs; };
  weather = [ (pkgs.callPackage ./waybar-weather.nix {}) ];
#  eclipse = import ./eclipse.nix { inherit pkgs; }; <--- Not finished
  dump = import ./pkg-dump.nix { inherit pkgs; };
  generated = import ./autogenerated.nix { inherit pkgs; };

in

builtins.concatLists [
  core
  dev
  kde
  hypr
  games
  comms
  simplex
  weather
  dump
  generated
]
